version: "3"

services:
    intro_web_api:
        container_name: intro_web_api
        build:
            context: server/
        ports:
            - "3000:3000"
        volumes: 
            - /app/data
        # environment: 
        depends_on: 
            - intro_web_db
    
    intro_web_front:
        container_name: intro_web_front
        build:
            context: noink/
        ports:
            - "8080:8080"
        volumes: 
            - /app/data
        # environment: 
        depends_on: 
            - intro_web_db
    
    intro_web_db:
        container_name: intro_web_db
        image: mongo:latest
        ports:
            - 27017:27017
        environment: 
            - MONGO_INITDB_DATABASE=noink
